### ISSUE TITLE
IUPAC handling in ExpansionHunter

### ISSUE THREAD

**Issue by raphaelbetschart** [gymrek-lab/TRTools#238]
Hi,

I'm running into some issues when using EnsembleTR with my ExpansionHunter VCF files.
The main issue is that the reference catalogue includes IUPAC nucleotides (for instance repeat structure `AARRG` at position chr4:39348424-39348479, taken from [https://github.com/Illumina/ExpansionHunter/blob/master/variant_catalog/hg38/variant_catalog.json](https://github.com/Illumina/ExpansionHunter/blob/master/variant_catalog/hg38/variant_catalog.json). This leads to an error in `utils.py` in the following line:
```
nucToNumber={"A":0,"C":1,"G":2,"T":3}
``` 

Should I just remove this entry or change the reference catalogue manually?
GangSTR and HipSTR catalogue both have the repeat structure `AAAAG`.

Thanks,
Raphael

**Comment by aryarm** [comment]
Thanks for reporting this issue, @raphaelbetschart! We've made an attempt at fixing it in https://github.com/gymrek-lab/EnsembleTR/pull/32

Can you try the new code and let us know if you're still having issues by reopening this issue?

**Comment by raphaelbetschart** [comment]
Hi @aryarm, the new code fixed the issue, thanks!
I found another small issue: `EnsembleTR --version` still reports version 1.0.0, but I can see that 1.0.1 was downloaded.
