### ISSUE TITLE
annotaTR - bcftools merge related issue for large cohorts

### ISSUE THREAD

**Issue by maegsul** [gymrek-lab/TRTools#244]
Hi,

First of all, thanks once again for developing TRTools! I have been using the newly implemented tool annotaTR particularly (v6.1.0), to annotate imputed TR VCFs with TRDS information to be used in plink2 for association testing (we have discussed this before, thank you also for the discussions on this earlier again!).

annotaTR now works really great and accurate based on the many tests I have performed, but the only problem I have currently is due to related to "bcftools merge" step actually.

If I use a large cohort (such as >40,000 samples), I try to split the input VCFs to be imputed into chunks of 8,000 samples for the Beagle imputation step, and as you recommend as well here (https://github.com/gymrek-lab/TRTools/blob/tr-gwas-tutorial/doc/VIGNETTE-GWAS-TUTORIAL.rst#step-14-merging-results-from-each-batch).

However, I realized that the chromosome-wide annotaTR fails and throws an error and exit when coming across with certain imputed TRs in the imputed VCFs (if I run --region specific annotaTR run, it works well, unless there is a problematic TR found in the provided region). The common pattern for these problematic imputed TRs are related to the order of different ALT alleles.

As you know bcftools merge trims the alleles (unfortunately), but this problem is solved by "--match-refpanel-on locid --update-ref-alt" options very nicely for most TRs; however still at certain TRs I see that the order of ALT alleles are impacted, and in these cases --update-ref-alt option cannot solve these cases. For instance, ALT1, ALT2, ALT3, ALT4 order in the original file becomes ALT1, ALT3, ALT2, ALT4 in the bcftools merge output, causing the problem.

The issue is perhaps expected as you also indicated it in the vignette (https://trtools.readthedocs.io/en/stable/source/annotaTR.html: "Use with caution as this assumes allele order is exactly the same between the refpanel and target VCF"), but I wanted to ask your advice on resolving this issue. For imputing large cohorts where you have to use bcftools merge, how do you avoid this problem, can you please help me with this? Thank you very much in advance!

Of note, I am using the most recent v4 imputation reference panel you have provided which have TR IDs (https://github.com/gymrek-lab/EnsembleTR/blob/fix-ref/README.md#version-iv-of-reference-snptr-haplotype-panel-for-imputation-of-tr-variants), and the most recent TRTools version (v6.1.0). Here is an example command I am using for annotaTR which works when --region parameter is used, but fails for chromosome-wide runs:

`annotaTR --vcf input_TRimputed_file_chr1.vcf.gz --out output_annotaTR_chr1 --vcftype hipstr --outtype pgen vcf --vcf-outtype z --chunk-size 10000 --dosages beagleap_norm --warn-on-AP-error --ref-panel ensembletr_refpanel_v4_chr1.vcf.gz --update-ref-alt`

And the error is as below:

>Traceback (most recent call last):
  File "/software/bin/annotaTR", line 10, in <module>
    sys.exit(run())
             ^^^^^
  File "/software/lib/python3.12/site-packages/trtools/annotaTR/annotaTR.py", line 721, in run
    retcode = main(args)
              ^^^^^^^^^^
  File "/software/lib/python3.12/site-packages/trtools/annotaTR/annotaTR.py", line 650, in main
    raise ValueError("--update-ref-alt set but the REF/ALT fields"
ValueError: --update-ref-alt set but the REF/ALT fields at chr1:2508612 are incompatible between the refpanel and target VCF

**Comment by gymreklab** [comment]
Thanks for reaching out and glad you are finding TRTools and annotaTR useful!

I am still working on figuring out what might be causing this as we did not yet encounter this error (although we anticipated bcftools merge could cause problems which is why we implement the check that failed: https://github.com/gymrek-lab/TRTools/blob/master/trtools/annotaTR/annotaTR.py#L49)

In theory if you used the same reference panel for each of the batches, the ref/alt alleles should be the same in the individual batches and (I thought) in the same order, but possibly truncated, after bcftools merge.

Would you be able to share what is in the REF/ALT fields for that locus that failed (chr1:2508612) for one of the batches before merging and the file after bcftools merge?

**Comment by maegsul** [comment]
Sure! Below are the EnsTR:chr1:2508612 info in each chunk (5 in total) and in bcftools merge output, together with the genotype fields of the first 6 samples in each file (so only in chunk1 and bcftools_merge files these 6 samples are the same individuals, the others are different individuals).

Thank you in advance for your help once again, and please let me know if you need more information - happy to share!

| File           | CHROM | POS     | ID                 | REF                 | ALT                                                                                                                 | QUAL | FILTER | INFO                                                                                  | FORMAT           | Sample1                                                                                 | Sample2                                                                     | Sample3                                                                                 | Sample4                                                                                 | Sample5                                                                                             | Sample6                                                                     |
|----------------|-------|---------|--------------------|---------------------|---------------------------------------------------------------------------------------------------------------------|------|--------|---------------------------------------------------------------------------------------|------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
| chunk1         | chr1  | 2508612 | EnsTR:chr1:2508612 | TTATATATATATATATATA | TTATATATATATATATATATA,TTATATATATATATATATATATA,TTATATATATATATATATATATATA,TTATATATATATATA,TTATATATATATATATATATATATATA | .    | PASS   | DR2=0.96,0.78,0.71,0.51,0.17;AF=0.1865,0.0128,0.0008,0.0006,0.0000;END=2508630;IMP    | GT:DS:AP1:AP2:GP | 1\|0:1.01,0,0,0,0:1,0,0,0,0:0.01,0,0,0,0:0,0.99,0.01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 1\|0:1,0,0,0,0:1,0,0,0,0:0,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                         | 0\|1:1,0,0,0,0:0,0,0,0,0:1,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 |
| chunk2         | chr1  | 2508612 | EnsTR:chr1:2508612 | TTATATATATATATATATA | TTATATATATATATATATATA,TTATATATATATATATATATATA,TTATATATATATATATATATATATA,TTATATATATATATA,TTATATATATATATATATATATATATA | .    | PASS   | DR2=0.96,0.83,0.42,0.62,0.15;AF=0.1926,0.0214,0.0008,0.0011,0.0000;END=2508630;IMP    | GT:DS:AP1:AP2:GP | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|0:0.04,0,0,0,0:0.04,0,0,0,0:0,0,0,0,0:0.96,0.04,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 1\|0:1,0,0,0,0:1,0,0,0,0:0,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 1\|0:1.02,0.05,0,0,0:0.95,0.05,0,0,0:0.07,0,0,0,0:0,0.88,0.07,0.05,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|1:1,0,0,0,0:0,0,0,0,0:1,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 |
| chunk3         | chr1  | 2508612 | EnsTR:chr1:2508612 | TTATATATATATATATATA | TTATATATATATATATATATA,TTATATATATATATATATATATA,TTATATATATATATATATATATATA,TTATATATATATATA,TTATATATATATATATATATATATATA | .    | PASS   | DR2=0.97,0.76,0.64,0.47,0.02;AF=0.1979,0.0083,0.0006,0.0003,0.0000;END=2508630;IMP    | GT:DS:AP1:AP2:GP | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 1\|0:1,0,0,0,0:1,0,0,0,0:0,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|1:1.02,0,0,0,0:0.02,0,0,0,0:1,0,0,0,0:0,0.98,0.02,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|0:0.03,0,0,0,0:0,0,0,0,0:0.03,0,0,0,0:0.97,0.03,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 |
| chunk4         | chr1  | 2508612 | EnsTR:chr1:2508612 | TTATATATATATATATATA | TTATATATATATATATATATA,TTATATATATATATATATATATA,TTATATATATATATATATATATATA,TTATATATATATATA,TTATATATATATATATATATATATATA | .    | PASS   | DR2=0.96,0.79,0.45,0.56,0.14;AF=0.2022,0.0126,0.0005,0.0006,0.0000;END=2508630;IMP    | GT:DS:AP1:AP2:GP | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|1:1,0,0,0,0:0,0,0,0,0:1,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 1\|0:1,0,0,0,0:1,0,0,0,0:0,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                         | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 |
| chunk5         | chr1  | 2508612 | EnsTR:chr1:2508612 | TTATATATATATATATATA | TTATATATATATATATATATA,TTATATATATATATATATATATA,TTATATATATATATATATATATATA,TTATATATATATATA,TTATATATATATATATATATATATATA | .    | PASS   | DR2=0.96,0.81,0.56,0.49,0.03;AF=0.1965,0.0152,0.0007,0.0007,0.0000;END=2508630;IMP    | GT:DS:AP1:AP2:GP | 0\|1:1,0,0,0,0:0,0,0,0,0:1,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 1\|0:1,0,0,0,0:1,0,0,0,0:0,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|1:1,0,0,0,0:0,0,0,0,0:1,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 1\|0:1,0,0,0,0:1,0,0,0,0:0,0,0,0,0:0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                         | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 |
| bcftools_merge | chr1  | 2508612 | EnsTR:chr1:2508612 | TTATA               | TTATATATA,TTATATA,TTATATATATA,T,TTATATATATATA                                                                       | .    | PASS   | END=2508630;IMP;AF=0.01406,0.19514,0.00068,0.00066,0;DR2=0.794,0.962,0.556,0.53,0.102 | GT:DS:AP1:AP2:GP | 2\|0:0,1.01,0,0,0:0,1,0,0,0:0,0.01,0,0,0:0,0,0,0.99,0,0.01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 | 2\|0:0,1,0,0,0:0,1,0,0,0:0,0,0,0,0:0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0             | 0\|0:0,0,0,0,0:0,0,0,0,0:0,0,0,0,0:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                         | 0\|2:0,1,0,0,0:0,0,0,0,0:0,1,0,0,0:0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 |

**Comment by maegsul** [comment]
Thanks a lot @gymreklab!

I had realized that I forgot to add the information on bcftools version I am using in my latest comment, and I added an edit for this. As indicated there, the version I have been using for this analysis was bcftools v1.7.

I have now made a quick test on this EnsTR:chr1:2508612 variant, using smaller subset of VCF chunks containing 6 samples each, using bcftools v1.20 merge as you recommended, and it worked! Interestingly, the output of bcftools merge in v1.20 was as below:

| #CHROM | POS     | ID                 | REF   | ALT                                           | QUAL | FILTER | INFO                                                                                  | FORMAT           |
|--------|---------|--------------------|-------|-----------------------------------------------|------|--------|---------------------------------------------------------------------------------------|------------------|
| chr1   | 2508612 | EnsTR:chr1:2508612 | TTATA | TTATATA,TTATATATA,TTATATATATA,T,TTATATATATATA | .    | PASS   | END=2508630;IMP;AF=0.19514,0.01406,0.00068,0.00066,0;DR2=0.962,0.794,0.556,0.53,0.102 | GT:DS:AP1:AP2:GP |

Here, compared to bcftools merge (v1.7) output of the table here https://github.com/gymrek-lab/TRTools/issues/244#issuecomment-2517314467, I think the first two ALT alleles were swapped. And downstream annotaTR run also worked on this bcftools merge v1.20 output.

I will soon make a test on full genome-wide data of >40k samples (5 chunks), but I am hoping that using bcftools v1.20 instead will work also for this full analysis.

By the way, [here ](https://github.com/samtools/bcftools/releases) there are some updates on bcftools merge since v1.7, but not quite sure which one fixes this issue.

Thank you very much once again for the help with this!

**Comment by gymreklab** [comment]
that's great news!! I will add a note to our tutorial and to the annotaTR page with a note about potential issues with older bcftools versions. Thanks for bringing this to our attention!
